keyword: لغه
framework:
  developer: 0
  language: ar
  login:
    email: scodoublet@yahoo.com
    password: "12345"
    onlineState: 1
  command:
    ignore:
      official: true
      unofficial: true
      self: true
  message:
    ignore:
      self: true
  subscriptions:
    messages:
      channel:
        enabled: true
        tipping: false
      private:
        enabled: true
        tipping: false
